### PR TITLE
fix(sass): fixes the production and dev server to run sass before webpack [3669]

### PR DESCRIPTION
**Pull request by janechu**
…pack

### CODE REVIEW

**Comment by awentzel** [comment]
So does this get run twice?  Immediately when starting webpack either in dev or prod and then at the end of Webpack after it does it's thing?

**Comment by janechu** [comment]
This gets run once before webpack gets hit so that no error is thrown, and then onBuildEnd in webpack because of the watcher which if it was onBuildStart it would prevent webpack from transpiling the application.

**Comment by awentzel** [comment]
Could you also update the README.  There is a *caution* notice explaining about the error and how to get around it. Now this isn't necessary anymore.  This also could be replaced with a little more info on why it runs twice.

**Comment by janechu** [comment]
The requested change to the markup has been made.

**Pull request merged**
